/**
 * Real LGA roster (data/LGA Employees/lga_employees.csv) for the Map feature's
 * Daily/Shift Report — replaces the smaller hand-picked associates.csv sample
 * previously baked into lib/mapShiftReportData.ts's ASSOCIATES_BY_SHIFT, so the
 * named roster (and the headcount derived from it) reflects LGA's actual crew.
 *
 * Avatars are copied into public/lga-employees/ (named `${slug(name)}.<ext>`) since
 * this app only serves static images out of /public, not /data. The source CSV's
 * `photo_filename` values don't exactly match the actual image files (mostly a
 * .jpg/.png extension mismatch, plus a few truncated filenames) — see the repo's
 * data/LGA Employees/employee images/ folder if this ever needs regenerating.
 * One associate (Maria Sora) has no source photo at all; she gets a local initials
 * placeholder (public/lga-employees/maria-sora.svg) instead of a broken image.
 *
 * Three rows in the source CSV have an invalid `shift` value (a specialty/role —
 * "Stainless Steel/Glass", "Curbside Attendant" — where Day/Swing/Graveyard should
 * be); those default to Day since the CSV doesn't otherwise say which shift they
 * work.
 */

export type LgaAssociate = {
  name: string;
  position: string;
  avatar: string;
};

export const LGA_ASSOCIATES_BY_SHIFT: Record<"day" | "swing" | "graveyard", LgaAssociate[]> = {
  day: [
    { name: "Amie Drammeh", position: "Custodian", avatar: "/lga-employees/amie-drammeh.png" },
    { name: "Angelo Rubio", position: "Custodian", avatar: "/lga-employees/angelo-rubio.png" },
    { name: "Antonia Luna", position: "Custodian", avatar: "/lga-employees/antonia-luna.png" },
    { name: "Blanca Quezada", position: "Custodian", avatar: "/lga-employees/blanca-quezada.png" },
    { name: "Bolivar Portilla", position: "Custodian", avatar: "/lga-employees/bolivar-portilla.png" },
    { name: "Candace Cooper", position: "Custodian", avatar: "/lga-employees/candace-cooper.png" },
    { name: "Carlos Gualpa", position: "Custodian", avatar: "/lga-employees/carlos-gualpa.png" },
    { name: "Claudia Pani Molina", position: "Custodian", avatar: "/lga-employees/claudia-pani-molina.png" },
    { name: "Don Alleyne", position: "Custodian/Trasher", avatar: "/lga-employees/don-alleyne.png" },
    { name: "Enrique Lazo Herrera", position: "Custodian", avatar: "/lga-employees/enrique-lazo-herrera.png" },
    { name: "Erlinda Achance", position: "Custodian", avatar: "/lga-employees/erlinda-achance.png" },
    { name: "Grechy Concha", position: "Custodian", avatar: "/lga-employees/grechy-concha.png" },
    { name: "Jerson Almonte", position: "Custodian", avatar: "/lga-employees/jerson-almonte.png" },
    { name: "Joel Navarro", position: "Custodial Lead", avatar: "/lga-employees/joel-navarro.png" },
    { name: "Jostin Campos Ronquillo", position: "Custodian", avatar: "/lga-employees/jostin-campos-ronquillo.png" },
    { name: "Juan Agudelo Vanegas", position: "Custodian/Trasher", avatar: "/lga-employees/juan-agudelo-vanegas.png" },
    { name: "Juan Jerez", position: "Custodian", avatar: "/lga-employees/juan-jerez.png" },
    { name: "Kadean Graham", position: "Clerk/Shipping & Receiving", avatar: "/lga-employees/kadean-graham.png" },
    { name: "Kelvin Lopez", position: "Curbside Attendant/Custodian", avatar: "/lga-employees/kelvin-lopez.png" },
    { name: "Lenin Calderon", position: "Floor Tech", avatar: "/lga-employees/lenin-calderon.png" },
    { name: "Leonor Asitimbay", position: "Custodian", avatar: "/lga-employees/leonor-asitimbay.png" },
    { name: "Luis Piguave", position: "Custodian", avatar: "/lga-employees/luis-piguave.png" },
    { name: "Mairoby Herrera Victoria", position: "Custodian", avatar: "/lga-employees/mairoby-herrera-victoria.png" },
    { name: "Makendy Joseph", position: "Custodian", avatar: "/lga-employees/makendy-joseph.png" },
    { name: "Manuel Calle", position: "Custodian", avatar: "/lga-employees/manuel-calle.png" },
    { name: "Marie Joseph Etienne", position: "Custodian", avatar: "/lga-employees/marie-joseph-etienne.png" },
    { name: "Narciza Velecela", position: "Custodian", avatar: "/lga-employees/narciza-velecela.png" },
    { name: "Neroly Peralta De Torres", position: "Custodian", avatar: "/lga-employees/neroly-peralta-de-torres.png" },
    { name: "Nestor Duarte", position: "Custodian", avatar: "/lga-employees/nestor-duarte.png" },
    { name: "Nicolasa Rosas", position: "Custodian", avatar: "/lga-employees/nicolasa-rosas.png" },
    { name: "Petronila Zarate", position: "Custodian", avatar: "/lga-employees/petronila-zarate.png" },
    { name: "Ponciano Toscano", position: "Custodian", avatar: "/lga-employees/ponciano-toscano.jpg" },
    { name: "Raash Alleyne", position: "Custodian", avatar: "/lga-employees/raash-alleyne.png" },
    { name: "Richard Awuah", position: "Custodian", avatar: "/lga-employees/richard-awuah.png" },
    { name: "Ronald Vinueza", position: "Custodial Lead", avatar: "/lga-employees/ronald-vinueza.png" },
    { name: "Rosa Pizarro", position: "Custodian", avatar: "/lga-employees/rosa-pizarro.png" },
    { name: "Rosa Yunga", position: "Custodian", avatar: "/lga-employees/rosa-yunga.png" },
    { name: "Rosario Paredes Juncal", position: "Custodian", avatar: "/lga-employees/rosario-paredes-juncal.png" },
    { name: "Ruth Pulla", position: "Custodian", avatar: "/lga-employees/ruth-pulla.png" },
    { name: "Segundo Villamar", position: "Custodian", avatar: "/lga-employees/segundo-villamar.png" },
    { name: "Shavar Davis", position: "Custodial Lead", avatar: "/lga-employees/shavar-davis.png" },
    { name: "Silvia Morocho", position: "Custodian", avatar: "/lga-employees/silvia-morocho.png" },
    { name: "Victor Mantilla", position: "Custodian", avatar: "/lga-employees/victor-mantilla.png" },
    { name: "Yesenia Bravo", position: "Custodian", avatar: "/lga-employees/yesenia-bravo.png" },
    { name: "Zoila Salomon", position: "Custodian", avatar: "/lga-employees/zoila-salomon.png" },
  ],
  swing: [
    { name: "Albaro Paulino", position: "Terrazzo/Floor Tech", avatar: "/lga-employees/albaro-paulino.png" },
    { name: "Anelise Andretta", position: "Custodian", avatar: "/lga-employees/anelise-andretta.png" },
    { name: "Angelica Matias", position: "Custodian", avatar: "/lga-employees/angelica-matias.png" },
    { name: "Angelica Roman", position: "Custodian", avatar: "/lga-employees/angelica-roman.png" },
    { name: "Blanca Diaz", position: "Custodian", avatar: "/lga-employees/blanca-diaz.png" },
    { name: "Cristhiam Fernandez", position: "Custodian", avatar: "/lga-employees/cristhiam-fernandez.png" },
    { name: "Elsa Joselin Gomez", position: "Custodian", avatar: "/lga-employees/elsa-joselin-gomez.png" },
    { name: "Eugenia Andrade", position: "Custodian", avatar: "/lga-employees/eugenia-andrade.png" },
    { name: "Everard Moncrieffe", position: "Custodian", avatar: "/lga-employees/everard-moncrieffe.png" },
    { name: "Gabriel Chimbo", position: "Floor Tech/Terrazzo", avatar: "/lga-employees/gabriel-chimbo.png" },
    { name: "Graciela Roa Moreno", position: "Custodian", avatar: "/lga-employees/graciela-roa-moreno.jpg" },
    { name: "Hafid Cuevas", position: "Custodian", avatar: "/lga-employees/hafid-cuevas.png" },
    { name: "Idalia Herrera", position: "Custodian", avatar: "/lga-employees/idalia-herrera.png" },
    { name: "Jacqueline Ludena Farfan", position: "Custodian", avatar: "/lga-employees/jacqueline-ludena-farfan.png" },
    { name: "Jerico Saul Lucas Mendoza", position: "Custodian", avatar: "/lga-employees/jerico-saul-lucas-mendoza.jpg" },
    { name: "Jose Guijarro", position: "Custodian/Trasher", avatar: "/lga-employees/jose-guijarro.png" },
    { name: "Jose Gutierrez", position: "Custodian", avatar: "/lga-employees/jose-gutierrez.png" },
    { name: "Joseph Pena", position: "Custodian", avatar: "/lga-employees/joseph-pena.png" },
    { name: "Laura Rubio", position: "Custodial Lead", avatar: "/lga-employees/laura-rubio.png" },
    { name: "Leonardo Amaya", position: "Custodian", avatar: "/lga-employees/leonardo-amaya.png" },
    { name: "Luis Duran", position: "Custodian", avatar: "/lga-employees/luis-duran.png" },
    { name: "Luis Huerta", position: "Custodian", avatar: "/lga-employees/luis-huerta.png" },
    { name: "Luis Minchala", position: "Custodian", avatar: "/lga-employees/luis-minchala.png" },
    { name: "Luis Rodriguez", position: "Custodial Lead", avatar: "/lga-employees/luis-rodriguez.png" },
    { name: "Marelis Fonseca", position: "Custodian", avatar: "/lga-employees/marelis-fonseca.png" },
    { name: "Margarita Guzman Garcia", position: "Custodian", avatar: "/lga-employees/margarita-guzman-garcia.png" },
    { name: "Maria Chimborazo", position: "Custodian", avatar: "/lga-employees/maria-chimborazo.png" },
    { name: "Maria Guzman", position: "Utility Technician (Curbside)/Floor Tech", avatar: "/lga-employees/maria-guzman.png" },
    { name: "Maria Lucas", position: "Custodian", avatar: "/lga-employees/maria-lucas.png" },
    { name: "Miller Parra", position: "Custodian", avatar: "/lga-employees/miller-parra.png" },
    { name: "Miriam Luz Valdez", position: "Custodian", avatar: "/lga-employees/miriam-luz-valdez.png" },
    { name: "Nancy Leon", position: "Custodian", avatar: "/lga-employees/nancy-leon.png" },
    { name: "Patrick Samuels", position: "Custodian", avatar: "/lga-employees/patrick-samuels.png" },
    { name: "Rafael Coronado", position: "Floor Tech/Utility Technician", avatar: "/lga-employees/rafael-coronado.png" },
    { name: "Rafael Polanco", position: "Custodian", avatar: "/lga-employees/rafael-polanco.png" },
    { name: "Raysa Alvarez", position: "Custodial Lead", avatar: "/lga-employees/raysa-alvarez.png" },
    { name: "Reginald Epps", position: "Floor Tech/Utility Technician", avatar: "/lga-employees/reginald-epps.png" },
    { name: "Rolando Rodriguez", position: "Floor Tech", avatar: "/lga-employees/rolando-rodriguez.png" },
    { name: "Ronald Marin", position: "Custodian", avatar: "/lga-employees/ronald-marin.png" },
    { name: "Rosa Garcia Palaguachi", position: "Custodian", avatar: "/lga-employees/rosa-garcia-palaguachi.png" },
    { name: "Saulo Ortiz", position: "Custodial Lead", avatar: "/lga-employees/saulo-ortiz.png" },
    { name: "Silvia Habana", position: "Custodian", avatar: "/lga-employees/silvia-habana.jpg" },
    { name: "Soyer Edemburgo", position: "Custodian", avatar: "/lga-employees/soyer-edemburgo.png" },
    { name: "Teofilo Moscoso", position: "Custodian/Trasher", avatar: "/lga-employees/teofilo-moscoso.png" },
    { name: "Timothy Stewart", position: "Floor Tech/Utility Technician", avatar: "/lga-employees/timothy-stewart.png" },
    { name: "Yerly Gutierrez", position: "Custodian", avatar: "/lga-employees/yerly-gutierrez.png" },
    { name: "Yesenia Paulino Sanchez", position: "Custodian", avatar: "/lga-employees/yesenia-paulino-sanchez.png" },
    { name: "Zoila Molina", position: "Custodian", avatar: "/lga-employees/zoila-molina.png" },
  ],
  graveyard: [
    { name: "Andres Rivas", position: "Custodian", avatar: "/lga-employees/andres-rivas.jpg" },
    { name: "Blanca Cajiga", position: "Custodian", avatar: "/lga-employees/blanca-cajiga.png" },
    { name: "Blanca Perez", position: "Custodian", avatar: "/lga-employees/blanca-perez.png" },
    { name: "Bryan Bonilla", position: "Floor Tech", avatar: "/lga-employees/bryan-bonilla.png" },
    { name: "Byron Chimbo", position: "Terrazzo/Floor Tech", avatar: "/lga-employees/byron-chimbo.png" },
    { name: "Carol Sanchez", position: "Gate/Carpet Specialist/Custodian", avatar: "/lga-employees/carol-sanchez.png" },
    { name: "Celso Prieto Arenas", position: "Custodial Lead", avatar: "/lga-employees/celso-prieto-arenas.png" },
    { name: "Dante Ponce", position: "Utility Technician/Floor Tech", avatar: "/lga-employees/dante-ponce.png" },
    { name: "Diana Garcia", position: "Custodian", avatar: "/lga-employees/diana-garcia.png" },
    { name: "Dignora Guzman", position: "Custodian", avatar: "/lga-employees/dignora-guzman.png" },
    { name: "Emilio Supo", position: "Floor Tech/Terrazzo", avatar: "/lga-employees/emilio-supo.png" },
    { name: "Erica Ibarra", position: "Power Washing/Floor Tech", avatar: "/lga-employees/erica-ibarra.png" },
    { name: "Eulalia Arce", position: "Custodian", avatar: "/lga-employees/eulalia-arce.png" },
    { name: "Evelin Sarmiento", position: "Custodian/People Mover/Escalator", avatar: "/lga-employees/evelin-sarmiento.png" },
    { name: "Fabian Lazo", position: "Terrazzo/Floor Tech", avatar: "/lga-employees/fabian-lazo.png" },
    { name: "Fanni Montenegro Minda", position: "Custodian", avatar: "/lga-employees/fanni-montenegro-minda.jpg" },
    { name: "Fatou Toure", position: "Custodian", avatar: "/lga-employees/fatou-toure.png" },
    { name: "Giovanna Gamarra", position: "Custodian", avatar: "/lga-employees/giovanna-gamarra.png" },
    { name: "Gissela Mero", position: "Custodian", avatar: "/lga-employees/gissela-mero.png" },
    { name: "Gloria Amendano", position: "Custodian", avatar: "/lga-employees/gloria-amendano.png" },
    { name: "Guillermo Torres", position: "Terrazzo/Floor Tech", avatar: "/lga-employees/guillermo-torres.png" },
    { name: "Hector Jerez", position: "Trasher/Custodian", avatar: "/lga-employees/hector-jerez.png" },
    { name: "Hector Rivera", position: "Custodian", avatar: "/lga-employees/hector-rivera.png" },
    { name: "Hema Thapa", position: "Custodian", avatar: "/lga-employees/hema-thapa.png" },
    { name: "Jonathan Montoya", position: "Custodian", avatar: "/lga-employees/jonathan-montoya.png" },
    { name: "Joselyn Campos", position: "Custodian", avatar: "/lga-employees/joselyn-campos.png" },
    { name: "Juan Avila", position: "Floor Tech/Restroom Specialist", avatar: "/lga-employees/juan-avila.png" },
    { name: "Juan Soto", position: "Custodian", avatar: "/lga-employees/juan-soto.png" },
    { name: "Juan Suarez", position: "Custodian", avatar: "/lga-employees/juan-suarez.png" },
    { name: "Kurwayne Lyte", position: "Power Washing/Floor Tech", avatar: "/lga-employees/kurwayne-lyte.png" },
    { name: "Leonardo Lucas", position: "Custodian/Trasher", avatar: "/lga-employees/leonardo-lucas.png" },
    { name: "Lilian Roldan Barrezueta", position: "Custodian", avatar: "/lga-employees/lilian-roldan-barrezueta.png" },
    { name: "Luis Zamora", position: "Custodian", avatar: "/lga-employees/luis-zamora.png" },
    { name: "Luzmi Zaraza", position: "Custodian", avatar: "/lga-employees/luzmi-zaraza.png" },
    { name: "Manuel Moreno", position: "Custodian", avatar: "/lga-employees/manuel-moreno.png" },
    { name: "Maria Bonilla", position: "Custodian", avatar: "/lga-employees/maria-bonilla.png" },
    { name: "Maria Cruz", position: "Custodian", avatar: "/lga-employees/maria-cruz.png" },
    { name: "Maria Gomez Rincon", position: "Custodian", avatar: "/lga-employees/maria-gomez-rincon.png" },
    { name: "Maria Moreno", position: "Custodian", avatar: "/lga-employees/maria-moreno.png" },
    { name: "Maria Sora", position: "Custodian", avatar: "/lga-employees/maria-sora.svg" },
    { name: "Maribel Velasco", position: "Custodian", avatar: "/lga-employees/maribel-velasco.png" },
    { name: "Maykol Orellana", position: "Custodian", avatar: "/lga-employees/maykol-orellana.png" },
    { name: "Mohammed Choudhury", position: "Floor Tech/Utility Technician", avatar: "/lga-employees/mohammed-choudhury.png" },
    { name: "Nancy Newman", position: "Custodian", avatar: "/lga-employees/nancy-newman.png" },
    { name: "Nancy Nicolalde Moreno", position: "Custodian", avatar: "/lga-employees/nancy-nicolalde-moreno.png" },
    { name: "Orlando Cabeza", position: "Custodian", avatar: "/lga-employees/orlando-cabeza.png" },
    { name: "Oscar Dario Alvarez Echavarria", position: "Custodian", avatar: "/lga-employees/oscar-dario-alvarez-echavarria.png" },
    { name: "Pedro Sialer", position: "Custodial Lead", avatar: "/lga-employees/pedro-sialer.png" },
    { name: "Ramon Osorio", position: "Custodian", avatar: "/lga-employees/ramon-osorio.png" },
    { name: "Rolfi Alburquerque", position: "Floor Tech/Utility Technician", avatar: "/lga-employees/rolfi-alburquerque.png" },
    { name: "Ronny Vertus", position: "Custodian", avatar: "/lga-employees/ronny-vertus.png" },
    { name: "Rosmery Ramirez", position: "Custodian", avatar: "/lga-employees/rosmery-ramirez.png" },
    { name: "Sileena Isaac", position: "Custodial Lead", avatar: "/lga-employees/sileena-isaac.png" },
    { name: "Sofia Chancusi", position: "Custodian", avatar: "/lga-employees/sofia-chancusi.png" },
    { name: "Timothy Wells", position: "Custodian", avatar: "/lga-employees/timothy-wells.png" },
    { name: "Victorino Caderao", position: "Custodian", avatar: "/lga-employees/victorino-caderao.png" },
    { name: "Yeison Estrella Arias", position: "Utility Technician (Curbside)/Floor Tech", avatar: "/lga-employees/yeison-estrella-arias.png" },
    { name: "Zaray Torres", position: "Custodian", avatar: "/lga-employees/zaray-torres.png" },
  ],
};

